import random

print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))
print(random.randrange(1, 3, 2))